### ISSUE TITLE
Fix metrics reporting URL

### ISSUE THREAD

**Issue by 0xcadams** [livepeer/livepeer.js#33]
The metrics reporting url should be constructed according to this discord discussion

https://discord.com/channels/423160867534929930/1011290512419999895

**Comment by 0xcadams** [comment]
We'll need this before we can cut a release with [this PR](https://github.com/livepeer/livepeer.js/pull/29) and add the player to Studio

**Comment by adamsoffer** [comment]
@0xcadams#2843 Can we cut a new release today? Shih-yu, Issac, and Claudio need to access it the player to finish work related to the docs and dashboard. I don't think the metrics reporting url needs to block this work since we can hotfix with the production url for metrics reporting. Thoughts? @ecmulli [suggested a reporting url to post to](https://discord.com/channels/423160867534929930/1011290512419999895/1017471914765189120) we can in the mean time so we won't have to cut a new release once the production url is available. 

@ecmulli @victorges Can you confirm this reporting url to be used in the interim?

**Comment by 0xcadams** [comment]
> @0xcadams#2843 Can we cut a new release today? Shih-yu, Issac, and Claudio need to access it the player to finish work related to the docs and dashboard. I don't think the metrics reporting url needs to block this work since we can hotfix with the production url for metrics reporting. Thoughts? @ecmulli [suggested a reporting url to post to](https://discord.com/channels/423160867534929930/1011290512419999895/1017471914765189120) we can in the mean time so we won't have to cut a new release once the production url is available.
> 
> @ecmulli @victorges Can you confirm this reporting url to be used in the interim?

Sounds good to me, I was hoping we could get this in beforehand but sounds like it's complicated.

**Comment by ecmulli** [comment]
I'll trust yall. I hate blocking things so if we can get people unblocked and just hotfix what we need to then I'm game.
